CREATE TABLE tb_user (
	id BIGINT NOT NULL AUTO_INCREMENT,
	user_name VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	email VARCHAR(255),
	create_time TIMESTAMP NOT NULL,
	PRIMARY KEY(id)
)CHARACTER SET = utf8;